name: CI

on:
  push:
    branches-ignore:
      - gh-pages
    paths-ignore:
      - '**.md'
    tags:
      - v*

jobs:
  lint:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '#skip-lint')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint

  build:
    runs-on: ubuntu-latest
    needs: lint
    if: "!contains(github.event.head_commit.message, '#skip-build')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true

  publish:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Install
        run: npm ci

      - run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - id: info
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Version
        run: npm version --no-git-tag-version ${{ env.VERSION }}

      - run: |
          git add -A
          git commit --no-verify -am "${{ env.VERSION }}"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
