name: CI

on:
  push:
    branches-ignore:
      - gh-pages
    paths-ignore:
      - '**.md'
    tags:
      - '*'

jobs:
  lint:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '#skip-lint')"
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v2
        with:
          cache: npm
          node-version: '17.x'

      - run: npm ci

      - run: npm run lint

  build:
    runs-on: ubuntu-latest
    needs: lint
    if: "!contains(github.event.head_commit.message, '#skip-build')"
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v2
        with:
          cache: npm
          node-version: '17.x'

      - run: npm ci

      - run: npm run build

  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true

  publish:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v2
        with:
          node-version: '17.x'
          registry-url: 'https://registry.npmjs.org'

      - run: npm ci

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
